### ISSUE TITLE
Graph is not rescaled after high predicted values disappear

### ISSUE THREAD

**Issue by yuri-zhuk** [loopandlearn/LoopFollow#121]
*[Environment]*
iPhone 12 Pro, iOS 14.3

*[Preconditions]*
Glucose entry (e.g. lunch) is added 4 hours into the future without bolus - predicted BG very high (~30 mmol).

*[Steps]*
Wait for the lunch, giving bolus as appropriate.

*[Actual result]*
The graph area in Loop Follow remains scaled for very high values, even though they are no longer present anywhere on the graph.

*[Expected result]*
The graph area is scaled back to whatever is the present highest value on the graph.

*[Workaround]*
Restarting the app fixes it.

**Comment by marionbarker** [comment]
## Status - this still needs to be fixed

Using latest LoopFollow (dev branch, commit 57e6350)

* I entered a bogus value of 399 into Apple Health: Loop, NS and LoopFollow picked it up - graph autoscaled
* I removed the bogus glucose value: Loop, NS and LoopFollow all show plots without the bogus value but the autoscaling still accommodates the bogus value
* waited for a few cycles and pulled down glucose - neither action changed the scaling
* restarted the app and scaling updated
