### ISSUE TITLE
All System Sounds Muted When App is Open

### ISSUE THREAD

**Issue by SteveB0115** [loopandlearn/LoopFollow#151]
I've recently started using this app and it's been great but I've ran into one issue. Whenever I have the app open in the background, all system sounds are muted (lock sound, keyboard clicks, notification sounds, etc...). I also cannot adjust my ringer volume from my physical volume buttons when the app is running, I can only adjust regular volume.

I've attempted a full restart of the phone thinking the issue was something else, but I am able to replicate this every single time I open the app, then close it (without using the app switcher to force close it). It seems as if the app is completely overriding my system sound. I've disabled all settings related to alarms and overriding sounds.
![unnamed (3)](https://user-images.githubusercontent.com/50989893/145504905-10f42988-22bc-438a-a770-fed190f2aef5.jpg)

iPhone 13 Pro Max, iOS 15.0

**Comment by SteveB0115** [comment]
After some more testing I've found a working solution. Turning off background refresh in the app settings fixes this issue. It appears that when the app is running in the background the phone thinks it's trying to play a sound. My first suspicion was that the Nightscout tab had something to do with it so I disabled all alarms there to no avail. Although I have found a temporary solution, I still wonder what's causing this issue in the first place.

**Comment by jonfawcett** [comment]
I have not heard any other reports of this and my own testing works just fine with all sounds. So I think it is something related to your phone.

Search the Fb group for battery and you’ll see how the sound works. It plays silent audio in the background to keep it alive. The app will not run in the background at all unless that toggle is enabled. So you will not receive alerts unless it is on screen.

**Comment by bjorkert** [comment]
Closing this issue as it has not been possible to reproduce the error. Please comment if this still happens.
