### ISSUE TITLE
Information Display Settings

### ISSUE THREAD

**Issue by mikebash** [loopandlearn/LoopFollow#158]
The Information Display Settings options do not show up on the initial load after installation via Test Flight (might be the same for building yourself).  Quitting the app and restarting resolves this issue.  

Trivial issue but documenting in case others are having issues (if so, close the app and restart the app to fix it).

**Comment by jonfawcett** [comment]
How long did you wait after entering your NS url? The BG values, treatments, and Loop data all run at slightly different timing, especially right after the url is first entered.

**Comment by mikebash** [comment]
I did a lot of searching on FB and in Github to see if it had been removed (for simplification or anything).  So it was a good amount of time (maybe 15 minutes).  And I was going in and out of screens to see if they had moved to new locations or there was another way to adjust the settings.  So I believe, maybe, enough time had passed but definitely wasn't purposely testing if time made a difference.  Swiping the app closed and restarting it instantly resolved it.

**Comment by mikebash** [comment]
And just to be crystal clear, this is what was missing ![image](https://user-images.githubusercontent.com/42122348/152707462-5e854499-cc7c-461e-8e01-043823aa5cfe.jpeg)

**Comment by clpetrone** [comment]
I am having the same issue.  Just did a rebuild tonight.  swiping and and restarting did NOT work. Help?

**Comment by clpetrone** [comment]
I got it..... thanks....

**Comment by bjornoleh** [comment]
I had this happening too now. Restarting the app worked on a real phone, but I could not get this to work in the simulator.

**Comment by bjorkert** [comment]
I believe this is resolved, otherwise please re-open.
