### ISSUE TITLE
Add “Clear cache” option for Loop Follow

### ISSUE THREAD

**Issue by bjornoleh** [loopandlearn/LoopFollow#159]
Browsers really like to hang on to cashed contents from NS sites, for a long long time. 

Example: If a change is made to NS code and this is deployed, unless forcefully clearing cache, the changes are often not seen in Nightscout. 

Both the Chrome and Safari apps on iOS has an option to clear cache/history/web site data, and this fixes the issue. Loop Follow does not have such an option, and I have found no reliable way to get changes in NS to take effect in the web browser of LF. 

I have tried deleting Safari cache, force closing LF, rebooting the phone. 

I guess deleting the app and rebuilding will do the trick, but then settings are lost. 

If settings could be saved/exported (as requested in https://github.com/jonfawcett/LoopFollow/issues/58), then this would probably help in dealing with the cache problem 

When searching for info on this, I came across something potentially useful here:

https://github.com/mozilla-mobile/firefox-ios/blob/master/Client/Frontend/Settings/Clearables.swift

I found the link here, and can’t guarantee it’s relevance for LF:

https://medium.com/@dakeshi/tips-for-wkwebview-that-will-keep-you-from-going-troubles-c1990851385c

**Comment by bjornoleh** [comment]
“Clear cache” option could be added either inside of Loop Follow, or as an iOS setting for the app.

**Comment by bjorkert** [comment]
Hi, thanks for the report. This has been fixed in this PR: https://github.com/loopandlearn/LoopFollow/pull/260
