### ISSUE TITLE
Disable auto-scroll?

### ISSUE THREAD

**Issue by clintonium-119** [loopandlearn/LoopFollow#162]
Thanks for the app.  I love it.  I do have one issue that I find detracts from it's use for me, which is the auto-scroll back to the realtime position.

I'll often find myself trying to scroll back to look at past boluses, for instance, and as I'm trying to examine them, it scrolls back to the start position.  I'll then scroll back, find what I'm looking for, and have it auto scroll back again.  And so on it goes until I give up and go to the Nightscout tab.  I'd love to use the main screen for retrospective checks, if possible, though.

I haven't seen any options to disable this in the settings menus.  Is this something you'd be interested in implementing, or considering if a PR was made to surface this option?

EDIT: perhaps even just disabling the auto-scroll back while the user is touching the graph would be sufficient, and not require an extra setting

**Comment by jonfawcett** [comment]
It auto scrolls when it downloads new readings. I did this to keep the latest reading on screen rather than always needing to scroll forward throughout the day to view the current info. Do you find you need more than the 5 minute interval to stay scrolled back for what you want to review?

**Comment by clintonium-119** [comment]
Thanks for the quick response.  Interestingly, for me, it's happening about every 6-11 seconds.  I just tried a moment ago after a fresh build today, and it did it 5 or 6 times in under a minute.

It doesn't seem to matter whether or not I keep actively scrolling or hold it in position, or whether I scroll via the top graph, or the mini-graph below.

5 minutes wouldn't be a problem.  I'm curious why mine is doing it so often.

**Comment by clintonium-119** [comment]
Could there be a Nightscout setting on my end causing it to refresh more often.  Perhaps my build is in some way corrupted if this is the first you've heard of this.  I've been using it for more than a year, and it's always been this way for me, so I'd assumed it was by design.

**Comment by jonfawcett** [comment]
Run a debug session with a break on controllers/graph.swift. Search it for “moveviewtoanimated” and add a break at that line. That is the only line in code that does this function. That should only trigger after each download of data. So I’d like to see if yours is triggering repeatedly. It should hit that break at startup pretty quickly but then not until the next reading. So let me know if it breaks over and over. 

This will hopefully let me see if it’s:
- something weird in the timers or processing code that is causing it to continually think it needs or is getting new data.
- something in the charts library interacting weird on your device (specific ios version, charts version, etc)

Make sure you code is newly downloaded when you do this test.

**Comment by clintonium-119** [comment]
Thanks.  I'll try tonight and get back to you.

**Comment by clintonium-119** [comment]
I gave it a shot, and looking at the logs, it seems to be the Nightscout BG Timer
```
##### started 5:10 bg timer: 116.0
Scale: 43.716976165771484
started 5 minute device status timer
yesterday 1647230400.0
today 1647316800.0
yesterday 1647252000.0
today 1647338400.0
yesterday 1647255600.0
today 1647342000.0
yesterday 1647264600.0
today 1647351000.0
2022-03-15 09:41:48.422458-0400 Loop Follow[5259:2737909] [connection] nw_endpoint_handler_set_adaptive_read_handler [C2.1 23.22.130.173:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
2022-03-15 09:41:48.422528-0400 Loop Follow[5259:2737909] [connection] nw_endpoint_handler_set_adaptive_write_handler [C2.1 23.22.130.173:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed
2022-03-15 09:43:47.472812-0400 Loop Follow[5259:2737918] [connection] nw_endpoint_handler_set_adaptive_read_handler [C3.1 54.243.238.66:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
2022-03-15 09:43:47.473097-0400 Loop Follow[5259:2737918] [connection] nw_endpoint_handler_set_adaptive_write_handler [C3.1 54.243.238.66:443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed
yesterday 1647230400.0
today 1647316800.0
yesterday 1647252000.0
today 1647338400.0
yesterday 1647255600.0
today 1647342000.0
yesterday 1647264600.0
today 1647351000.0
##### started 10 second bg timer
##### started 10 second bg timer
##### started 10 second bg timer
##### started 10 second bg timer
##### started 10 second bg timer
##### started 10 second bg timer
##### started 10 second bg timer
##### started 10 second bg timer
##### started 10 second bg timer
##### started 30 second bg timer
yesterday 1647230400.0
today 1647316800.0
yesterday 1647252000.0
today 1647338400.0
yesterday 1647255600.0
today 1647342000.0
yesterday 1647264600.0
today 1647351000.0
##### started 30 second bg timer
##### started 5:10 bg timer: 128.0
started 5 minute device status timer
```

Not long after startup, it begins setting 10 second bg timers, and scrolling back at that point.  Eventually it changes to 30 seconds, then 5 minutes.  The 5 minute device status timers seem to be setting at the correct cadence.

As far as my settings go, I haven't connected my Dexcom account.  I could try that, but I don't have it ("Show Dexcom Settings") checked, so I assumed that's fine.  I do have "Download Loop/FreeAPS data" checked, and the "BG Update Delay" set to 30 seconds in advanced settings.

**Comment by clintonium-119** [comment]
Ok.  I thought I was using the latest.  I did pull the latest from `main`, but I obviously must be building off of a cache or something.  I didn't clean the build folder.  I'll get back to you if it's all good after the rebuild.  Sounds like that'll be the case.

**Comment by jonfawcett** [comment]
Oh wait. I didn't push it yet to GitHub :) Nevermind that last comment.

**Comment by aug0211** [comment]
Around line 550 in the Graphs file:

```
        // Move to current reading everytime new readings load
        //Auggie - comment this out, incredibly annoying when trying to look at old BGs
        /*
        BGChart.moveViewToAnimated(xValue: dateTimeUtils.getNowTimeIntervalUTC() - (BGChart.visibleXRange * 0.7), yValue: 0.0, axis: .right, duration: 1, easingOption: .easeInBack)
         */
    }
```

**Comment by aug0211** [comment]
I have a PR up now to fix this.

https://github.com/loopandlearn/LoopFollow/pull/236
