### ISSUE TITLE
Graph in loop follow app not showing full information since using G7

### ISSUE THREAD

**Issue by Unicorns5-5** [loopandlearn/LoopFollow#200]
![575BCCD5-9792-4142-9C06-676036FBED97](https://user-images.githubusercontent.com/74317771/232332721-ba9cbe37-93a1-4046-aa3e-343d91174dd0.png)

**Comment by mjliedtke** [comment]
Anymore details?  What's your data source Dexcom, nightscout?

**Comment by Unicorns5-5** [comment]
It appears to be that it was due to a false crazy high reading recorded on the Dexcom during warm up of new sensor (first time using G7). Once that rogue reading was 24 hours old the graph returned to normal. Others had the same issue and were able to reassure me it would return to normal and it did We use Dexcom and nightscout through loop.  On 22 Apr 2023, at 01:21, mjliedtke ***@***.***> wrote:﻿
Anymore details?  What's your data source Dexcom, nightscout?

**Comment by mjliedtke** [comment]
Awesome.  Thanks

**Comment by bjorkert** [comment]
LoopFollow is now filtering out those high values. Thanks for reporting this.
