### ISSUE TITLE
iOS 17 Calendar Entries Broken

### ISSUE THREAD

**Issue by aug0211** [loopandlearn/LoopFollow#201]
Looks like Loop Follow needs update how it is writing entries to the calendar in order to work in iOS 17. Details here:

https://developer.apple.com/documentation/eventkit/accessing_calendar_using_eventkit_and_eventkitui

This is currently broken in iOS 17. Entries into the calendar for Watch and CarPlay will not work.

**Comment by bjorkert** [comment]
Hi! Thanks for reporting this. LoopFollow has been updated. See PR below. 
https://github.com/loopandlearn/LoopFollow/pull/208

This works well for my iOS 17 beta iPhone. Would it be possible for you to test and confirm as well?

**Comment by aug0211** [comment]
Tested and confirmed (Xcode 15 and iOS 17)! Thanks!

Heads up, SAGE and CAGE calls are using %20, and iOS 17 will want + instead. The new "Carbs today" correctly uses +, just need to update SAGE and CAGE for iOS 17 the same way. Figured I'd note here as iOS 17 prep related stuff.

**Comment by bjorkert** [comment]
> Tested and confirmed (Xcode 15 and iOS 17)! Thanks!
> 
> Heads up, SAGE and CAGE calls are using %20, and iOS 17 will want + instead. The new "Carbs today" correctly uses +, just need to update SAGE and CAGE for iOS 17 the same way. Figured I'd note here as iOS 17 prep related stuff.

Thanks! About %20 and iOS 17, it should surely be fixed. I did some googling on this but could not find anything related to that, do you have a link? Just curious.

**Comment by aug0211** [comment]
> > Tested and confirmed (Xcode 15 and iOS 17)! Thanks!
> > Heads up, SAGE and CAGE calls are using %20, and iOS 17 will want + instead. The new "Carbs today" correctly uses +, just need to update SAGE and CAGE for iOS 17 the same way. Figured I'd note here as iOS 17 prep related stuff.
> 
> Thanks! About %20 and iOS 17, it should surely be fixed. I did some googling on this but could not find anything related to that, do you have a link? Just curious.

I don’t have a link, I think I just put this together by referencing other code that worked somewhere else - and did some trial and error testing to identify it was the %20 causing the issue, but that iOS 17 was fine with + instead.
