### ISSUE TITLE
Show Dexcom data not working 

### ISSUE THREAD

**Issue by PeterSchioeth** [loopandlearn/LoopFollow#212]
A quick Loop Follow question: 
I get the date from Night Scout by adding the URL. No problem. But when I chose show Dexcom data and write my son's username and password, nothing happens. I doesn't get any data. I use the username from his Clarity and Dexcom profile on a nonUS account. Is there somthing I am missing?

**Comment by bjorkert** [comment]
LoopFollow is now updated, Dexcom was not working for non-US users. Please update to latest version of LoopFollow and try again, please conform if it is works for you as well.

**Comment by PeterSchioeth** [comment]
Just did the update and now it works!!! Thanks 🙏

**Comment by jannyg** [comment]
Works here as well. Thanks for your efforts @bjorkert!
