### ISSUE TITLE
Revise colours for high BGs and COB pred BGs

### ISSUE THREAD

**Issue by bjornoleh** [loopandlearn/LoopFollow#221]
The support for iAPS is working great!

We should probably revise the colours for high BGs and COB pred BGs, as these are the same, and makes it hard to see what is what. Let’s see if I’ll get to it, or if someone else will do it first. 

![IMG_5741](https://github.com/loopandlearn/LoopFollow/assets/63544115/7884aa53-316b-4247-9395-626319d5b985)

**Comment by bjornoleh** [comment]
PR #225  copies colour assets from https://github.com/Artificial-Pancreas/iAPS/tree/main/FreeAPS/Resources/Assets.xcassets/Colors and use these for COB, IOB, UAM and ZT predictions.

This fixes the issue with identical colours for hgh BGs and COP predictions, while also aligning all colours with iAPS predictions. 

Tested and confirmed to work:

**COB:**
![image](https://github.com/loopandlearn/LoopFollow/assets/63544115/b5a7f798-3581-4e52-baea-ca497cbb2e32)



**IOB:**
![image](https://github.com/loopandlearn/LoopFollow/assets/63544115/b7182ff7-1ef4-4077-9b8d-250d173ba3be)


**UAM:**
![image](https://github.com/loopandlearn/LoopFollow/assets/63544115/5d0ac0c4-488b-4fa6-a8f5-052e6ec31689)


**ZT:**
![image](https://github.com/loopandlearn/LoopFollow/assets/63544115/1781f71a-2490-4c57-a46e-6e2800dd9c38)

**Comment by bjorkert** [comment]
Closing this since the PR is merged.
