### ISSUE TITLE
iAPS (dev) SMB Boluses no longer display in Loop Follow

### ISSUE THREAD

**Issue by flyingpie101** [loopandlearn/LoopFollow#222]
A recent change has occurred in iAPS with respect to recording boluses in Nightscout.
Manual Boluses are now recorded as follows: 
![image](https://github.com/loopandlearn/LoopFollow/assets/11539494/d710487e-7ded-4469-820a-07516fc21b7e)

and SMB (auto boluses) like so:
![image](https://github.com/loopandlearn/LoopFollow/assets/11539494/ffe0f85f-74d5-40d8-ac87-04fec17621a3)

Can we have LoopFollow include Treatment type : SMB in it's display of insulin given ?

![IMG_0708](https://github.com/loopandlearn/LoopFollow/assets/11539494/fd7c9fed-6929-4de2-94c0-6b37e0b75521)
![SCR-20230928-d9e](https://github.com/loopandlearn/LoopFollow/assets/11539494/77199295-291c-409b-a30f-e38064d3cc24)

**Comment by flyingpie101** [comment]
The change in iAPS (dev) was from the following
https://github.com/Artificial-Pancreas/iAPS/commit/24c5abb58ec706024e3e7fc2a9b662e06378421e

**Comment by bjorkert** [comment]
> The change in iAPS (dev) was from the following [Artificial-Pancreas/iAPS@24c5abb](https://github.com/Artificial-Pancreas/iAPS/commit/24c5abb58ec706024e3e7fc2a9b662e06378421e)

Thanks!

**Comment by bjorkert** [comment]
main updated with fix for this. Thanks again for the iAPS sha.

**Comment by flyingpie101** [comment]
I updated LF Dev and the fix is there.   Is there a large difference between Main and Dev ?

**Comment by bjorkert** [comment]
main and dev is equal as it is now.
