### ISSUE TITLE
Double bolus shown in main tab and a single bolus in Nightscout

### ISSUE THREAD

**Issue by flyingpie101** [loopandlearn/LoopFollow#239]
As per screenshots.  You will see 2 4.5U boluses. In NS there is only 1. 

![image](https://github.com/loopandlearn/LoopFollow/assets/11539494/92e82e41-bb0f-47c6-ab80-fa17f78663d8)
![image](https://github.com/loopandlearn/LoopFollow/assets/11539494/5ccc6191-8f7b-4bbd-9f48-7a9c44627acd)

**Comment by bjorkert** [comment]
<img width="357" alt="CleanShot 2023-10-24 at 19 09 25@2x" src="https://github.com/loopandlearn/LoopFollow/assets/12718238/236af86f-253d-47b5-b068-daf5acfa1d61">

If you look at the data in Nightscout, the value is there twice. It must be a but in the iAPS uploader to nightscout.

**Comment by bjorkert** [comment]
Forgot to close this issue.
