### ISSUE TITLE
Browser Build Error

### ISSUE THREAD

**Issue by fzzarf220** [loopandlearn/LoopFollow#256]
Hi,

I've been trying to do a browser build and keep on getting the following error:

<img width="1128" alt="image" src="https://github.com/loopandlearn/LoopFollow/assets/5897081/c38ac577-e437-4f51-a9bc-4d4371059377">

What am I doing wrong?

<img width="816" alt="image" src="https://github.com/loopandlearn/LoopFollow/assets/5897081/81e705f8-c370-409e-98df-152919ec4026">

This is the first time i've had this issue happen.  Tried looking online, but wasnt able to see any solutions.

**Comment by bjorkert** [comment]
Hi,

You have this error:
https://loopkit.github.io/loopdocs/gh-actions/gh-errors/#error-provisioning-profile

error: Provisioning profile "match AppStore com.***.Daneen.LoopFollow" has app ID "com.***.Daneen.LoopFollow", which does not match the bundle ID "com.***.'Daneen'.LoopFollow".

This must be related to your customization of the code you have done in your branch.
BR/Jonas

**Comment by fzzarf220** [comment]
> Hi,
> 
> You have this error: https://loopkit.github.io/loopdocs/gh-actions/gh-errors/#error-provisioning-profile
> 
> error: Provisioning profile "match AppStore com._**.Daneen.LoopFollow" has app ID "com.**_.Daneen.LoopFollow", which does not match the bundle ID "com.***.'Daneen'.LoopFollow".
> 
> This must be related to your customization of the code you have done in your branch. BR/Jonas

Thank you for the quick reply.

The customization you're seeing, where the its "com.<TEAM_ID>.<NAME>.LoopFollow" has been a customization that I've used to successfully build before (for over a year).    Its only with the most recent code, when I merged it in, do I see this new issue.    

By the way, I'm not seeing that error you're seeing; where did you get that log?

Thanks

**Comment by bjorkert** [comment]
The error is in the build log, https://github.com/fzzarf220/LoopFollow/actions/runs/7560254375/job/20585879384
![CleanShot 2024-01-17 at 21 06 29@2x](https://github.com/loopandlearn/LoopFollow/assets/12718238/fbb2105a-2337-41e4-89aa-65575da515f7)

May I ask what is the purpose of the customization. I guess that the changes we have done to allow building multiple instances of the app is the cause of the problems you are gettin now.

**Comment by fzzarf220** [comment]
> The error is in the build log, https://github.com/fzzarf220/LoopFollow/actions/runs/7560254375/job/20585879384 ![CleanShot 2024-01-17 at 21 06 29@2x](https://private-user-images.githubusercontent.com/12718238/297504344-fbb2105a-2337-41e4-89aa-65575da515f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1MjIzOTAsIm5iZiI6MTcwNTUyMjA5MCwicGF0aCI6Ii8xMjcxODIzOC8yOTc1MDQzNDQtZmJiMjEwNWEtMjMzNy00MWU0LTg5YWEtNjU1NzVkYTUxNWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDIwMDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNWE5Nzg4ZGZhNTZiMWYwNWNiNTc4ZGZjN2ZiZGExOTk3ZWY4ZThjZjU5MDhiZjBkYWRkYjM3MTNmNzU4ODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sky4z2KNLwO5I_Cj5jYCguoxIVg04S2uD7AhAxA3VT0)
> 
> May I ask what is the purpose of the customization. I guess that the changes we have done to allow building multiple instances of the app is the cause of the problems you are gettin now.

UGH, my error!!!! Thank you, you are right.  There are quotes chars when I set the name.  So dumb, been chasing the wrong error all this time.

Yes correct, that customization was to allow for multiple version of the app to run on a single iphone.  I was going to share the PR for my changes, but then you guys beat me to it.

I need to eventually switch over to the current way of doing it.   

Thank you for helping me debug this issue.

Issue resolved.
