### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by VillumsNightscout** [loopandlearn/LoopFollow#28]
It would be great feature if location of the Looper could be integrated.

Similar to Find My’. 

Possibly implemented with a swipe function to navigate between screens.

A shortcut to ‘Find My’ with open on Looper location could be simpler implementation approach.

**Comment by jonfawcett** [comment]
This is interesting. What are the main benefits you see versus just using Find My, Life 360, etc.

**Comment by VillumsNightscout** [comment]
It is the same functionality and information as Find My and Life360, however, keeping with ambition of having a single App presenting all information about the Looper (young child), the location is something we switch to quite frequently. Hence the wish to have it available from within the LoopFollow-app.

Ultimately, alarms for change of location (leaving school, friends house) paired with BG level or Loop prediction, could be a possibility - as well as triggering overrides based on this data.

**Comment by bjorkert** [comment]
We're tidying up the LoopFollow repo and noticed this issue has been inactive for a while. We're closing it to keep things organized. If this is still a concern or you have further insights, please don't hesitate to reopen or create a new issue.

Thanks for your understanding!
