### ISSUE TITLE
Mac app crashes on BG pinch to zoom

### ISSUE THREAD

**Issue by mikebash** [loopandlearn/LoopFollow#283]
I have Loop Follow installed on my Mac using macOS Sonoma. I have noticed that any time I try to change the "zoom" on the BG graph via pinch to zoom, the app crashes. I used browser build and TestFlight to install on the Mac. The same build does not crash on my phone, only the Mac. 

Please advise if you'd like a crash report or additional details.

**Comment by bjorkert** [comment]
Hi! I just tried this but could not make it crash. If you could catch what line it crashes on using the debugger it would help.

**Comment by marionbarker** [comment]
Closed because we could not reproduce the problem. You can still continue the conversation even with this Issue closed.
