### ISSUE TITLE
Feature Request:  Using the Apple Contacts Watch complication to Display BG

### ISSUE THREAD

**Issue by flyingpie101** [loopandlearn/LoopFollow#293]
As recently implemented in iAPS 4, have same functionality applied to LF.

Updates a contact record with a picture of BG (and various other options)

Anecdotally, this accomplishes  a similar need as the Calendar display complication, but with Contacts.

https://github.com/Artificial-Pancreas/iAPS/pull/595

https://github.com/Artificial-Pancreas/iAPS/pulls?q=is%3Apr+author%3Ayurique

**Comment by bjorkert** [comment]
See: https://github.com/loopandlearn/LoopFollow/pull/342
