### ISSUE TITLE
Information Display Settings

### ISSUE THREAD

**Issue by JSmith856** [loopandlearn/LoopFollow#302]
The data isn’t populating in any of the fields in the latest version 2.2.2. I am unable to view that data on 2 separate phones when building with XCode. Everything is up to date on our machines. 17.5.1 IOS and 3.2.3 build (57) 6/10/2024 of LoopCaregiver (I wished it would just say Loop instead of LoopCaregiver under the Loop icon. 
![IMG_2674](https://github.com/loopandlearn/LoopFollow/assets/53193870/e7a563b8-dbd0-4009-8645-24a2bc43ed1b)
.

**Comment by marionbarker** [comment]
When the information table does not populate, that means no data is coming in from Nightscout.
* First go to your Nightscout site and make sure it is operating

If it is, then tap on settings in LoopFollow and then show Nightscout settings. If NS Status does not say OK, you know to update the URL and/or Token until it does say OK.

Feel free to post a graphic of that screen as a comment in this Issue if you continue to have trouble.

If these steps solve it, then please close with a comment that says Resolved.

**Comment by marionbarker** [comment]
About your comment:
>  I wished it would just say Loop instead of LoopCaregiver under the Loop icon.

Do you mean under the blue LoopFollow icon - you want it to say Loop?

We need to add nicer instructions for modifying the display name. This link is all we have now:
* https://github.com/loopandlearn/LoopFollow?tab=readme-ov-file#display-name-updates

**Comment by marionbarker** [comment]
Closing because this was a Nightscout issue, not a LoopFollow bug. You can still continue the conversation even with this Issue closed.
