### ISSUE TITLE
SMB on version 2.2.3 still are blue circle

### ISSUE THREAD

**Issue by charlesstyves** [loopandlearn/LoopFollow#310]
I have install the new version 2.2.3 and SMB boluses are still blue circle. No blue triangle are visible. Manual and automatic boluses have the same icons.

Using : iAPS 2.3.3 and Nighscout Pro service. Same result on iOS 16 and iOS 17 (two differents phones)

**Comment by bjorkert** [comment]
I wonder if there is any difference between iAPS and Trio here, we are only testing with Trio since that is what we officially support. If you want, you could PM me an adress of the nightscout account including a token (if required) and I can have a quick look, no promises :)

**Comment by marionbarker** [comment]
Pretty sure the addition of an isSMB flag came after version 2.3.3 of iAPS. Once Trio is released; if you transfer to that app, it should start working for you.

**Comment by charlesstyves** [comment]
Thanks, I will check this when I will do the move.

**Comment by bjorkert** [comment]
We’ll consider this issue closed for now. If you encounter any further problems after switching to Trio, feel free to create a new issue.
