### ISSUE TITLE
One prediction line option?

### ISSUE THREAD

**Issue by charlesstyves** [loopandlearn/LoopFollow#311]
The integration of the four prediction lines of iAPS/Trio is great on the version 2.2.3. Thanks a lot.
 
However, our day care educator prefered the previous version when only one prediction line was shown. It was easier for her to get a quick look and see if everything will look great in the next 30 minutes.

Could it be possible to get an option to mask some prediction lines (ex : the zero temp) or show only the more accurate one at this moment (ex : COB when carbs active, UAM when no COB and BG not follow the IOB curve, etc.).

Could be great for basic user as daycare, school or occasionnaly care giver (like grand parents).

Thanks!

**Comment by marionbarker** [comment]
Thanks for your comment. 

There are definitely more Trio changes in the future. No promises but @bjorkert is pretty innovative and responsive.

**Comment by charlesstyves** [comment]
That’s me that thanks in you and the rest of people working on DIY apps.

Forums generally talk about issues and not enought about the good things.

Our son was diagnosed one year before, in July. As every diabete story, it has been a crash course year.

We started on pump on mid January. 3 days with standard Dash, and then, switch to iAPS. iAPS gave us the chance to get 70% time in range with h1b1c of 6,7% for a 4 years old kid with pratically no food restriction.

LoopFollow has been a big part of this success by giving us the opportunity to assist the day care easily on working day and accelerate my learning curve of iAPS by distance. 

Thanks for all the team to help us giving better life for our children!

**Comment by bjorkert** [comment]
Thanks for the great feedback! I get how a single prediction line can be easier for daycare staff and occasional caregivers.

I would prefer if Trio could create an extra "simplified prediction cruve", I’ll check with the Trio developers to see if they see that as a possibility.

By the way, now that some days have passed, how are they handling the four curves? Or have you waited with the update?

**Comment by charlesstyves** [comment]
Your are right, LoopFollow is a distance viewer of the controller. It would be better to add this functionality directly to Trio/iAPS.

We have made the update on all linked iPhone. After some days, we have learn the daycare staff to don’t look at the purple curve (zero temp) and check for the first curve that cross the 4 mmol line to see if there is a risk of hypoclycemia in the next 30 minutes. If no one cross it in the next 30 min., no specific monitoring is required. Finally, this method work not so bad.

Thanks!

**Comment by bjorkert** [comment]
Sounds great, thanks for the input, closing this issue.
