### ISSUE TITLE
Loop follow shows wrong target and ISF

### ISSUE THREAD

**Issue by kristinkand** [loopandlearn/LoopFollow#325]
After the last update to version 2.2.5 I’ve noticed that Loop follow shows the wrong target and ISF.

I’ve checked the settings on the loopers phone and everything there is correct: target 5.5 and ISF between 5 and 7 depending on the time of the day.
I haven’t managed to pinpoint what causes the change of the display or what brings it back to show the correct values.

![IMG_A889F608CBB3-1](https://github.com/user-attachments/assets/0f90c9b4-045c-49d3-9ac2-16eebd322f6f)

**Comment by bjorkert** [comment]
Hi! That looks very strange, would you be comfortable sending me the nightscout address and token (if needed) so I can take a look at the data? jonas@bjorkert.se

BR/Jonas

**Comment by bjorkert** [comment]
@kristinkand Can we close this one now when it showing the correct values.

The issue was that Nightscout reported incorrect values in current profile and I gave the hint to toggle an override to force Loop to push the settings to Nightscout.

**Comment by kristinkand** [comment]
Sure! Thank you so much for the hint and all your support. Best KristinSent from my iPhoneOn 20 Aug 2024, at 21:03, Jonas Björkert ***@***.***> wrote:﻿
@kristinkand Can we close this one now when it showing the correct values.
The issue was that Nightscout reported incorrect values in current profile and I gave the hint to toggle an override to force Loop to push the settings to Nightscout.
