### ISSUE TITLE
LF (remote) branch on Trio shows ISF in mixed units

### ISSUE THREAD

**Issue by flyingpie101** [loopandlearn/LoopFollow#332]
Our units are mmol
Using the LF Remote branch and the Trio remote branch (latest as of today)
As per screen shot, ISF shows as 3.7 -> 67.0
should show as 3.7 -> 3.7 (that is what is shown in NS)

![IMG_2974](https://github.com/user-attachments/assets/8ccce2c5-4beb-4529-abdf-dfc76e9219d8)

**Comment by bjorkert** [comment]
Thanks for the report!
Solved by: https://github.com/loopandlearn/LoopFollow/commit/0b5f0f29cdfc80f65d089ececbdf1973196823a8
