### ISSUE TITLE
Feature request: Follow Multiples T1Ds

### ISSUE THREAD

**Issue by clvsjr9** [loopandlearn/LoopFollow#65]
We suggest the possibility of incorporating the ability to monitor, by parents and / or caregivers, more than one patient. Registration of list of nigthscouts sites and the possibility of visual choice of each patient to be accompanied at a time with the update of the screen to reflect the selection of the chosen patient.

**Comment by jonfawcett** [comment]
This is definitely a feature that is needed for people with multiple T1’s in their household. It’s also a fairly large undertaking to do it correctly, so I can’t promise any sort of timeline for when it will happen. 

In the meantime, a workaround is to build the app twice to your phone. FYI, this may use massive amounts of battery If you have both with background refresh enabled. All you should need to do is edit the bundle identifier. Just under the team selection for signing, you can do something as simple as change that to add a 2 at the end. For instance Build the app, then change the identifier to com.xxxxxxxx.LoopFollow2 and build it again. The xxxxxx represents your unique Apple ID that is filled in automatically, so leave that at whatever is listed.

I haven’t tried this to see if anything else causes an issue, so if you try it and have a problem, let me know.

If you want to change the app icon for one or both so they can be differentiated easily, follow the same instructions as loopdocs under the customization section.

**Comment by clvsjr9** [comment]
No urgency.  It will be useful when it can be implemented without excessive battery usage and within a single Loop Follow app ...

One example:

https://github.com/someoneAnyone/Nightscouter

**Comment by bjornoleh** [comment]
Just to confirm that the solution above works:

I have built Loop Follow as two separate apps by editing the bundle identifier, and replacing the icon set as described in Loopdocs ( https://loopkit.github.io/loopdocs/build/code_customization/#loop-logo )

The icons can be found in LoopFollow/Resources/Assets.xcassets

The icons are overwritten when cloning using the "Open in XCode" feature, so keep them handy somewhere for future updates.

**Comment by bjornoleh** [comment]
Hi @jonfawcett, I have two LF apps with different bundle identifiers that I maintain for our two loopers, so that those can coexist on one phone, and with different icons and a few more tweaks. 

I have now started to upload critical apps to Testflight, to be able to fix things on the go, without bringing the Mac. This works well for Loop / FAX and Loop Follow, but I have not managed to upload the second LF app to Testflight, as it will register as the same app when uploading. I have been messing around trying to change the product name etc, but I did not succeed. 

Is there a relatively easy way make Testflight recognise the two apps as different apps?

Thanks!

**Comment by jonfawcett** [comment]
I would have assumed an alternate bundle identifier would be sufficient. So I’m not sure of a solution if that didn’t work.

**Comment by bjornoleh** [comment]
Ok, thanks. I guess I could try your TestFlight version though, but not sure if that will work either then. I might sign up for one seat to see how it goes, if it’s not too much trouble.

**Comment by bjorkert** [comment]
This was solved with the 2nd and 3rd LoopFollow repo.
