### ISSUE TITLE
Info Table - Font Size

### ISSUE THREAD

**Issue by clvsjr9** [loopandlearn/LoopFollow#82]
Suggestion for adjusting the font size in the Info Table (Title and Data). I recommend System 13 to be equivalent to the one used in the item Server info.

**Comment by clvsjr9** [comment]
Better yet: option to adjust the font size in the settings button

**Comment by bjorkert** [comment]
Closing this issue. If it is still of interest, please comment with motivation on how the proposed font change would improve the app, and if possible, include a screenshot.
